# Generated by Django 4.1.3 on 2022-11-15 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_firs_name_author_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
