# Generated by Django 4.1.3 on 2022-11-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_firs_name_partner_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='address',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='partner',
            name='book',
            field=models.ManyToManyField(blank=True, through='core.BookLoan', to='core.book'),
        ),
        migrations.AddField(
            model_name='partner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
